### ISSUE TITLE
CSS wraps unordered-list from bottom, causing uneven row sizes

### ISSUE THREAD

**Issue by mikecrinite** [mikecrinite/craigslist-global#4]

**Comment by thatarchguy** [comment]
Might have to move away from css multi-column https://stackoverflow.com/a/14925546

**Comment by mikecrinite** [comment]
Yeah I'm thinking I'll have to add JS to do other stuff like showing/hiding
search options depending on the selected category (haven't even really
looked into how hard that'd be in Go)
